About Name component
acm-ucr/developer-station pull request #14
Opened 2024-10-09 06:50 UTC by d-leeee

Added tailwind custom configs
Added About Name component
![Screenshot 2024-10-08 at 11 49 38 PM](https://github.com/user-attachments/assets/22530861-b1dd-43ac-8bf7-85ab83e11a7e)

2024-10-09 06:54 UTC, d-leeee commented
![Screenshot 2024-10-08 at 11 53 31 PM](https://github.com/user-attachments/assets/074f3ff1-f647-45ed-b062-2915a6330033)

2024-10-14 01:28 UTC, stanleylew5 requested changes
About.tsx, and place it within a folder within the components folder called home. you'll need to create the home folder

2024-10-14 01:28 UTC, stanleylew5 commented on src/components/about.tsx
> +}
you're passing in props here, but we actually don't need props passed in here haha should've specified in the issue description. we'll have some actual text on the figma there soon. for now you can just put the lorem ipsum text in

2024-10-14 01:28 UTC, stanleylew5 commented on src/components/about.tsx
> +      <div className="text-7xl">About</div>
use vh, vw units instead ex: text-[5vw] here's an example of what they are

https://www.sitepoint.com/css-viewport-units-quick-start/

We'll go over this at tomorrow's meeting

2024-10-14 01:28 UTC, stanleylew5 commented on src/components/about.tsx
> +      <div className="pb-20 text-9xl">{name}</div>
same thing as above comment

2024-10-14 01:28 UTC, stanleylew5 commented on tailwind.config.ts
> +      },
let's not hardcode in values for font size and line height.  we'll go more in depth into this tomorrow but if you don't want to wait til tomorrow try experimenting with vh vw, % units.

2024-10-14 01:42 UTC, stanleylew5 requested changes

2024-10-14 01:42 UTC, stanleylew5 commented on src/components/about.tsx
> +    <div className="flex flex-col items-center text-center font-Malayalam font-normal">
```suggestion
    <div className="flex flex-col items-center text-center font-Malayalam">
```
not needed, does nothing

2024-10-21 18:52 UTC, merged