Created Course Name Component
acm-ucr/developer-station pull request #15
Opened 2024-10-12 04:58 UTC by carlahauu

<img width="1075" alt="image" src="https://github.com/user-attachments/assets/878677a2-0ed8-4d93-9c49-a45335156d18">

2024-10-14 01:42 UTC, stanleylew5 requested changes

2024-10-14 01:42 UTC, stanleylew5 commented on tailwind.config.ts
> +      },
let's not hardcode in values for font size and line height. we'll go more in depth into this tomorrow but if you don't want to wait til tomorrow try experimenting with vh vw, % units.

2024-10-14 01:42 UTC, stanleylew5 commented on src/components/CourseName.tsx
> +    <div className="flex w-full flex-col items-center rounded-2xl bg-dark-cyan text-center font-Malayalam font-normal">
```suggestion
    <div className="flex w-full flex-col items-center rounded-2xl bg-dark-cyan text-center font-Malayalam">
```
not needed, does nothing

2024-10-21 21:03 UTC, shahdivyank commented on src/components/CourseName.tsx
> +      <div className="pb-16 pt-16 text-6xl text-white">{name}</div>
16 is lowk a big value, there should be a better way to center/align this

2024-10-30 22:33 UTC, shahdivyank approved these changes

2024-10-30 22:34 UTC, merged