darsh175223/try course button
acm-ucr/developer-station pull request #16
Opened 2024-10-12 22:37 UTC by darsh175223

I created a new file in the components folder for the Try Course button. The colors and shapes of the button are in line with the figma design

2024-10-14 01:44 UTC, stanleylew5 commented
make sure you link your issue, also sync your github emails or use one account (whichever one was invited) for your issues

2024-10-14 02:14 UTC, stanleylew5 requested changes
tldr, this code overcomplicates the issue it can be something similar to 

<div className="bg-green-500 rounded-full py-2 px-4">
        <button className="text-2xl bg-[#eaf7dc] rounded-full px-4 py-2 text-black">TRY COURSE</button>
      </div>
      
      obviously some styling needs to be done but it takes care of all the absolute inset positioning and all that you're going through right now. try following the code above this comment. and import your colors within the tailwind config file

2024-10-14 02:14 UTC, stanleylew5 commented on src/components/try-course-button.tsx
> +      {/* Main button */}
```suggestion

```

2024-10-14 02:14 UTC, stanleylew5 commented on src/components/try-course-button.tsx
> +      {/* Larger shape beneath */}
```suggestion

```

2024-10-14 02:14 UTC, stanleylew5 commented on src/components/try-course-button.tsx
> +        <button className="relative w-[96%] rounded-full bg-[#eaf7dc] px-12 py-3 text-xl font-bold uppercase text-black shadow-md transition-all duration-300 ease-in-out hover:shadow-lg">
```suggestion
        <button className="relative w-[96%] rounded-full bg-[#eaf7dc] px-12 py-3 text-xl font-bold text-black shadow-md">
```

2024-10-14 02:14 UTC, stanleylew5 commented on src/components/try-course-button.tsx
> +        <button className="relative w-[96%] rounded-full bg-[#eaf7dc] px-12 py-3 text-xl font-bold uppercase text-black shadow-md transition-all duration-300 ease-in-out hover:shadow-lg">
also, use dark mode colors since we're going to start with dark mode first. instead of hard coding #eaf7dc, add the color within tailwind config file. pull from dev first though `git pull origin`

2024-10-14 02:14 UTC, stanleylew5 commented on src/components/try-course-button.tsx
> +          <span className="relative z-10">TRY COURSE</span>
```suggestion
          <p>TRY COURSE</p>
```

2024-10-14 02:14 UTC, stanleylew5 commented on src/components/try-course-button.tsx
> +          <div className="absolute inset-0 rounded-full bg-gradient-to-b from-transparent to-[#eaf7dc] opacity-50"></div>
```suggestion
        
```
not quite sure what this is for it does nothing

2024-10-14 02:14 UTC, stanleylew5 commented on src/components/try-course-button.tsx
> +    <div className="relative inline-block w-[20%] p-1.5">
```suggestion
    <div className="relative w-[20%] p-1.5">
```

2024-10-20 00:28 UTC, darsh175223 commented
I changed the colors to dark mode, removed all the tags that don't serve a purpose and changed the text and the widths to be dependent on the screen size(ex: text-[5vw]).

2024-10-21 18:35 UTC, merged