Rattahamberg/courses layout
acm-ucr/developer-station pull request #17
Opened 2024-10-13 19:30 UTC by rattahamberg

![image](https://github.com/user-attachments/assets/a85a6604-a282-479b-b287-487d3686e525)

2024-10-13 19:38 UTC, rattahamberg reviewed
Formatting touched all of these files for some reason; I didn't change any of this manually.

2024-10-14 02:32 UTC, stanleylew5 requested changes
delete entire .idea folder.

2024-10-14 02:32 UTC, stanleylew5 commented on tailwind.config.ts
> +      },
solve your merge conflict, if you don't know how we'll cover this tomorrow

2024-10-14 02:32 UTC, stanleylew5 commented on src/components/courselayout.tsx
> +
props do not need to be passed here, sorry for having unclear issues but we'll replace the lorem ipsum/description with actual text soon but you can just put lorem ipsum text for now

2024-10-14 02:32 UTC, stanleylew5 commented on src/components/courselayout.tsx
> +    <div className="mx-auto flex w-full max-w-[calc(100%-100px)] flex-col items-center rounded-[20px] bg-course-layout-background/80 p-8 text-center font-Malayalam font-normal">
the tailwind classes that are being used here are overcomplicated please ask for help tomorrow

2024-10-14 02:32 UTC, stanleylew5 commented on src/components/courselayout.tsx
> +      <div className="pb-4 pt-8 text-center font-Malayalam text-[80px] font-normal leading-[100px]">
values here are hardcoded like 80 px, use tailwind classes instead

2024-10-14 02:32 UTC, stanleylew5 commented on src/app/page.tsx
> +        title="Our Projects"
no props need to be passed

2024-10-14 20:45 UTC, rattahamberg commented
Fixed (I think) all requested changes.

2024-10-15 20:16 UTC, stanleylew5 requested changes

2024-10-15 20:16 UTC, stanleylew5 commented on src/components/courselayout.tsx
> +      <div className="text-[1.15vw]">
```suggestion
      <div className="text-xl">
```
this isn't technically "header" text we can just leave it as text-xl

2024-10-15 20:16 UTC, stanleylew5 commented on src/components/courselayout.tsx
> +    <div className="bg-transparent-80 p-auto font-Malayalam mx-auto flex w-[95vw] flex-col items-center rounded-[1vw] bg-devstation-green-200 p-[2.5vw] text-center font-normal">
```suggestion
    <div className="bg-transparent-80 p-auto mx-auto flex w-[95vw] flex-col items-center rounded-xl bg-devstation-green-200 p-[2.5vw]">
```

2024-10-15 20:16 UTC, stanleylew5 commented on src/components/courselayout.tsx
> +    <div className="bg-transparent-80 p-auto font-Malayalam mx-auto flex w-[95vw] flex-col items-center rounded-[1vw] bg-devstation-green-200 p-[2.5vw] text-center font-normal">
```suggestion
    <div className="bg-transparent-80 w-11/12 flex flex-col items-center rounded-xl bg-devstation-green-200 p-[2.5vw]">
```
a lot of the classes you added are not needed

2024-10-15 20:16 UTC, stanleylew5 commented on src/components/courselayout.tsx
> +      <div className="text-[1.15vw]">
```suggestion
      <div className="text-lg">
```
this is technically not header text, just the above was

2024-10-15 20:16 UTC, stanleylew5 commented on src/components/courselayout.tsx
> +    <div className="bg-transparent-80 p-auto font-Malayalam mx-auto flex w-[95vw] flex-col items-center rounded-[1vw] bg-devstation-green-200 p-[2.5vw] text-center font-normal">
if you're curious as to why, feel free to ask us in the general chat

2024-10-15 21:28 UTC, rattahamberg commented
Simplified the CSS some more.

2024-10-15 22:39 UTC, stanleylew5 requested changes

2024-10-15 22:39 UTC, stanleylew5 commented on src/components/courselayout.tsx
> +      <div className="text-[1.15vw]">
```suggestion
      <div className="text-lg">
```

2024-10-15 22:50 UTC, merged