Home screen / Landing Page
acm-ucr/developer-station pull request #21
Opened 2024-10-14 21:10 UTC by hackinrish

<img width="1512" alt="Screenshot 2024-10-14 at 2 04 40 PM" src="https://github.com/user-attachments/assets/1c75d4b0-f8d6-4858-8971-e9a5ed68fa6d">

- Created landing screen for home page based on the figma with minor stylistic differences in color and font, this is something which currently needs to be worked on, specifically applying custom fonts and colors

- Closes issue #2

2024-10-14 22:36 UTC, shahdivyank commented
merge conflicts

2024-10-14 22:37 UTC, shahdivyank commented on src/app/page.tsx
> +        <Image
self closing image

2024-10-14 22:37 UTC, shahdivyank commented on src/app/page.tsx
> +            <div className="h-8 w-8 rounded-full bg-gray-300"></div>
self closing

2024-10-14 22:38 UTC, shahdivyank commented on public/landingpagetrainpath.png
making a landing folder for the landing images

2024-10-18 23:16 UTC, stanleylew5 commented
![image](https://github.com/user-attachments/assets/093c2cf5-b259-408e-9157-b2fcc904b90d)

make sure you add a gradient instead of using blue-950, feel free to add the colors within tailwind config file. and also increase the size of the "developer station" text

2024-10-21 18:47 UTC, stanleylew5 requested changes
change the gradient to go from top to bottom since that's what the figma shows, also you're missing an element 
![image](https://github.com/user-attachments/assets/2b0c4efd-29d3-4525-bfa7-6933eaf510ec)
that circle thingie. also merge the pr that'll convert your png to webp that's related to this pr

2024-10-25 17:57 UTC, merged