Added the error page component
acm-ucr/developer-station pull request #42
Opened 2024-11-04 01:51 UTC by darsh175223

Added an image of the Error page in dark mode. Added text "404 Error" in the middle of the image.

- resolves #31

2024-11-04 09:26 UTC, stanleylew5 requested changes
first, replace the webp file with an SVG file, you can do so by copying the elements you want from the figma as an SVG and then creating a SVG file and then copying in the text into the SVG file.

make sure you remove your webp files in the process

2024-11-04 09:26 UTC, stanleylew5 commented on src/components/ErrorPageDark.tsx
> +        />
```suggestion
        <Image
          src={errorImageDark}
          alt="Error background"
          fill
          priority
        />
```

2024-11-04 09:26 UTC, stanleylew5 commented on src/components/ErrorPageDark.tsx
> +      <p className="font-sans-serif absolute -translate-y-16 text-[8vw] text-yellow-400 drop-shadow-[0_0_15px_rgba(250,204,21,0.8)]">
```suggestion
      <p className="font-sans-serif absolute -translate-y-[10vh] text-[8vw] text-yellow-400 drop-shadow-[0_0_15px_rgba(250,204,21,0.8)]">
```

2024-11-04 09:26 UTC, stanleylew5 commented on src/components/ErrorPageDark.tsx
> +      <p className="font-sans-serif absolute -translate-y-16 text-[8vw] text-yellow-400 drop-shadow-[0_0_15px_rgba(250,204,21,0.8)]">
use color from figma for yellow -- add it within tailwind config file

2024-11-18 10:48 UTC, shahdivyank approved these changes

2024-11-18 10:48 UTC, merged